apiVersion: apps/v1
kind: Deployment
metadata:
  name: copy-node-labels
spec:
  selector:
    matchLabels:
      app: copy-node-labels
  template:
    metadata:
      labels:
        app: copy-node-labels
    spec:
      containers:
      - name: copy-node-labels
        image: docker.k3s.differentpla.net/copy-node-labels
        volumeMounts:
          - mountPath: /certs
            name: certs
      volumes:
        - name: certs
          secret:
            secretName: copy-node-labels-tls
