apiVersion: apps/v1
kind: Deployment
metadata:
  name: copy-node-labels
spec:
  selector:
    matchLabels:
      app: copy-node-labels
  template:
    metadata:
      labels:
        app: copy-node-labels
    spec:
      serviceAccountName: copy-node-labels
      containers:
      - name: copy-node-labels
        image: copy-node-labels
        ports:
          - containerPort: 8443
        volumeMounts:
          - mountPath: /certs
            name: certs
      volumes:
        - name: certs
          secret:
            secretName: copy-node-labels
