apiVersion: apps/v1
kind: Deployment
metadata:
  name: copy-node-labels
spec:
  selector:
    matchLabels:
      app: copy-node-labels
  template:
    metadata:
      labels:
        app: copy-node-labels
      annotations:
        differentpla.net/copy-node-labels: "topology.kubernetes.io/region, topology.kubernetes.io/zone"
    spec:
      serviceAccountName: copy-node-labels
      containers:
      - name: copy-node-labels
        image: docker.k3s.differentpla.net/copy-node-labels
        ports:
          - containerPort: 8443
        volumeMounts:
          - mountPath: /certs
            name: certs
      volumes:
        - name: certs
          secret:
            secretName: copy-node-labels
