apiVersion: apps/v1
kind: Deployment
metadata:
  name: dump-env-vars
spec:
  selector:
    matchLabels:
      app: dump-env-vars
  template:
    metadata:
      annotations:
        differentpla.net/in-deployment: bar
        differentpla.net/copy-node-labels: topology
      labels:
        app: dump-env-vars
    spec:
      initContainers:
        - name: init
          image: busybox
          command: ['sh', '-c', 'sleep 60']
      containers:
        - name: dump-env-vars
          image: docker.k3s.differentpla.net/dump-env-vars
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
          env:
            # This is populated correctly.
            - name: IN_DEPLOYMENT
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['differentpla.net/in-deployment']
            # But this is blank, implying that we're too late when mutating the annotations.
            - name: TOPOLOGY_REGION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['topology.kubernetes.io/region']
            - name: TOPOLOGY_ZONE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['topology.kubernetes.io/zone']
            # This is set kinda late, so why doesn't the above work?
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

# Doesn't work, which implies it's too late. However: status.podIP is a thing, and that's assigned _really_ late, so why
# not?

# The annotation changes happen, but they're not reflected in the downwardAPI.

# And we can't easily use the K8s api in the pod, because that requires code/script changes, and rbac changes.
# What about access to _current_ pod vs. access to the node in general?
